---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name:
        - kitty
        - neofetch
        - discord
        - flameshot
        - neovim
        - polybar
        - solaar
        - spotify
        - tmux

  - name: copy zshrc
    copy:
      src: ./files/zshrc
      dest: /home/sam/.zshrc
      owner: sam
      group: sam

  - name: copy Xresources
    copy:
      src: ./files/Xresources
      dest: /home/sam/.Xresources
      owner: sam
      group: sam

  - name: copy tmux.conf
    copy:
      src: ./files/tmux.conf
      dest: /home/sam/.tmux.conf
      owner: sam
      group: sam

  - name: copy profile
    copy:
      src: ./files/profile
      dest: /home/sam/.profile
      owner: sam
      group: sam

  - name: copy p10k.zsh
    copy:
      src: ./files/p10k.zsh
      dest: /home/sam/.p10k.zsh
      owner: sam
      group: sam

  - name: copy gitmessage
    copy:
      src: ./files/gitmessage
      dest: /home/sam/.gitmessage
      owner: sam
      group: sam

  - name: copy gitconfig
    copy:
      src: ./files/gitconfig
      dest: /home/sam/.gitconfig
      owner: sam
      group: sam

  - name: copy dmenurc
    copy:
      src: ./files/dmenurc
      dest: /home/sam/.dmenurc
      owner: sam
      group: sam

  - name: copy alacritty.yml
    copy:
      src: ./files/alacritty.yml
      dest: /home/sam/.alacritty.yml
      owner: sam
      group: sam

  - name: copy fonts.conf
    copy:
      src: ./files/fonts.conf
      dest: /home/sam/.fonts.conf
      owner: sam
      group: sam

  - name: copy rofi
    copy:
      src: ./files/rofi
      dest: /home/sam/rofi
      owner: sam
      group: sam
