---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name:
        - kitty
        - neofetch
        - discord
        - flameshot
        - neovim
        - polybar
        - solaar
        - spotify
        - tmux
