---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name:
        - kitty
        - neofetch
        - discord
        - flameshot
        - neovim
        - polybar
        - solaar
        - spotify
        - tmux
        - moar

  - name: copy zshrc
    copy:
      src: ./files/zshrc
      dest: /home/sam/.zshrc
      owner: sam
      group: sam

  - name: copy Xresources
    copy:
      src: ./files/Xresources
      dest: /home/sam/.Xresources
      owner: sam
      group: sam

  - name: copy tmux.conf
    copy:
      src: ./files/tmux.conf
      dest: /home/sam/.tmux.conf
      owner: sam
      group: sam

  - name: copy profile
    copy:
      src: ./files/profile
      dest: /home/sam/.profile
      owner: sam
      group: sam

  - name: copy i3 config
    copy:
      src: ./files/i3/config
      dest: /home/sam/.i3/config
      owner: sam
      group: sam

  - name: copy p10k.zsh
    copy:
      src: ./files/p10k.zsh
      dest: /home/sam/.p10k.zsh
      owner: sam
      group: sam

  - name: copy gitmessage
    copy:
      src: ./files/gitmessage
      dest: /home/sam/.gitmessage
      owner: sam
      group: sam

  - name: copy gitconfig
    copy:
      src: ./files/gitconfig
      dest: /home/sam/.gitconfig
      owner: sam
      group: sam

  - name: copy dmenurc
    copy:
      src: ./files/dmenurc
      dest: /home/sam/.dmenurc
      owner: sam
      group: sam

  - name: copy alacritty.yml
    copy:
      src: ./files/alacritty.yml
      dest: /home/sam/.alacritty.yml
      owner: sam
      group: sam

  - name: copy fonts.conf
    copy:
      src: ./files/fonts.conf
      dest: /home/sam/.fonts.conf
      owner: sam
      group: sam

  - name: copy rofi
    copy:
      src: ./files/rofi
      dest: /home/sam/
      owner: sam
      group: sam

  - name: copy rofi rose-pine theme
    copy:
      src: ./files/local/share/rofi/themes/rose-pine.rofi
      dest: /home/sam/local/share/rofi/themes/
      owner: sam
      group: sam

  - name: copy fonts
    copy:
      src: ./files/fonts
      dest: /home/sam/.fonts/
      owner: sam
      group: sam

  - name: copy config
    copy:
      src: ./files/config/
      dest: /home/sam/.config/
      owner: sam
      group: sam

  - name: copy oh my zsh
    copy:
      src: ./files/oh-my-zsh
      dest: /home/sam/.oh-my-zsh
      owner: sam
      group: sam
