#!/bin/bash

declare -A options
options['Rose Pine']='rose-pine'
options['Rasmus']='rasmus'

echo "Available themes:"
PS3="Pick a number:"

selectedTheme=''
indicator='➡'
files="$HOME/ansible-desktop/files"
config="$HOME/.config"

# https://en.wikipedia.org/wiki/ANSI_escape_code
# https://tldp.org/HOWTO/Bash-Prompt-HOWTO/x329.html
color='\033[3;34m' # Blue
nc='\033[0;0m' # No color

select option in "${!options[@]}"; do
  echo -e "$indicator $option"
  selectedTheme=${options[${option}]}
  break
done

# Make a backup of Xresources if it does not exists
if ! [ -f $HOME/.Xresources-bkp ]
then
  cp $HOME/.Xresources $HOME/.Xresources-bkp
fi

# Copy matching Xresources file
cp \
  "$files/Xresources.d/Xresources.$selectedTheme" \
  "$HOME/.Xresources"

xrdb ~/.Xresources

# modify Rofi config

rofiNewThemePath="@import \"~/.config/rofi/colors/$selectedTheme.rasi\""
launchers="$config/rofi/launchers"
powermenu="$config/rofi/powermenu"

sed -i '$d' $launchers/type-1/shared/colors.rasi
echo $rofiNewThemePath >> $launchers/type-1/shared/colors.rasi

sed -i '$d' $powermenu/type-2/shared/colors.rasi
echo $rofiNewThemePath >> $powermenu/type-2/shared/colors.rasi

# modify $config/kitty/color.conf
sed -i '$d' $config/kitty/color.conf
echo "include ./colors/$selectedTheme.conf" >> $config/kitty/color.conf

# Reload i3 and kitty
xdotool key super+shift+r
echo -e "🐱 To reload kitty press$color Ctrl+Shift+F5 $nc"
echo "✨ All Done."
