#!/bin/bash

declare -A options
options['Rose Pine']='rose-pine'
options['Rasmus']='rasmus'

echo "Available themes:"
PS3="Pick a number:"

selectedTheme=''
indicator='➡'
files="$HOME/ansible-desktop/files"
config="$HOME/.config"

# https://en.wikipedia.org/wiki/ANSI_escape_code
# https://tldp.org/HOWTO/Bash-Prompt-HOWTO/x329.html
color='\033[3;34m' # Blue
nc='\033[0;0m' # No color

select option in "${!options[@]}"; do
  echo -e "$indicator $option"
  selectedTheme=${options[${option}]}
  break
done

# Make a backup of Xresources if it does not exists
if ! [ -f $HOME/.Xresources-bkp ]
then
  cp $HOME/.Xresources $HOME/.Xresources-bkp
fi

# Copy matching Xresources file
cp \
  "$files/Xresources.d/Xresources.$selectedTheme" \
  "$HOME/.Xresources"

xrdb ~/.Xresources

# TODO modify $config/rofi/launchers/type-1/shared/colors.rasi
# TODO modify $config/rofi/powermenu/type-2/shared/colors.rasi
# TODO modify $config/kitty/color.conf

echo -e "$indicator Press ${color}Super+Shift+R${nc} to reload i3"
echo -e "$indicator Press ${color}Ctrl+Shift+F5${nc} to reload kitty"
echo "✨ All Done."
